# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UploadImage' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/Crash'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
  # Pods for UploadImage

  target 'UploadImageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UploadImageUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
